### ISSUE TITLE
#1 Ideas

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#1]
Задача:
Составить список идей, которые можно реализовать в проекте:
1) Особенности игрового процесса
2) Особенности регистрации и хранения данных о пользователе
3) Особенности реализации проекта
4) Особенности дизайна

Вероятно добавление/изменение классификации идей

https://github.com/malinink/games/wiki/Ideas

**Comment by malinink** [comment]
@AlfredJones Согласен

**Comment by malinink** [comment]
Дальнейшее обновление идей будет в wiki
