### ISSUE TITLE
Создать модель и миграцию состояния доски

### ISSUE THREAD

**Issue by bubrick-old** [malinink/games#10]
Родительская задача #5
Исполнитель @Ananaskelly 

Модель [BoardInfo](https://github.com/malinink/games/wiki/Database) содержит
- **game_id** (integer) (внешний ключ, связана m:1  с Game #8 **id**)
- figure (tinyInteger)
- position (smalltInteger)
- color (bool)
- special (bool)
- turn_number (smallInteger)

связана m:1 с Game #8 **id**
Теги: model

**Comment by Ananaskelly** [comment]
Хотела бы взять это задание
