### ISSUE TITLE
Идентификация токеном

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#101]
Родительская задача #100 
Исполнитель @

Описание
Класс, который будет обрабатывать запросы с name  _authentification_. Получает token клиента и проверяет его соответствие в бд. Если ошибок нет - идентифицирует пользователя и отправляет сообщение об успешном прохождении аутентификации, в противном случае - сообщение об ошибке.
Класс должен реализовывать интерфейс #98
Формат запроса [тут](https://github.com/malinink/games/wiki/Protocol#%D0%98%D0%B4%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%BE%D0%BC)  

Теги: backend

**Comment by malinink** [comment]
Этот класс также должен реализовывать интерфейс из #98

**Comment by Ananaskelly** [comment]
+
