### ISSUE TITLE
Подписка

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#102]
Родительская задача #100
Исполнитель @

Описание
Класс, который обрабатывает запросы с name _subscribe_. Получает game_id игры, на которую хочет подписаться клиент и, если не произошло ошибок, отправляет id последнего хода.
Класс должен реализовывать интерфейс #98.
Формат запроса [тут](https://github.com/malinink/games/wiki/Protocol#%D0%9F%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0)

Теги: backend

**Comment by learp** [comment]
+
