### ISSUE TITLE
Обновление статуса текущей игры

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#104]
Родительская задача #89 
Исполнитель @

Описание
Создать метод в контроллере, который вызывает метод  getCurrentGameStatus (App: User), если  запрос с name subscribe  получил ответ success, и обновляет лейбл в navigationbar. 

Теги: frontend

**Comment by malinink** [comment]
метод реализуем по пути /ajax/_appropriate_name_/
соответственно метода возвращает json

**Comment by IrenJones** [comment]
+

**Comment by IrenJones** [comment]
@malinink 
Ишью некорректно сформулировано

Но я не знаю, как исправить и как его сделать

**Comment by malinink** [comment]
@IrenJones 
Мне кажется я понял в чем проблема, изучине внимательно протокол(на случай если я что-то упустил из виду).

Если все верно, то нам нехватает события начала игры. Я мог бы предложить добавить ещё один статус хода, что-то вроде "start" или "begin" и тем самым уведомлять оппонента о начале игры, собственно процесс обновления частей страницы можно запускать при наступлении этого события.
Ну и сделать соответствующие экшены в ajax контроллере, а на стороне клиента - встравку этих данных в нужное место.

Можно на текущий момент действительно ограничиться только лишь плашкой статуса игры. и менять поиск игры на игру. Ну и соответственно инициализацией самой игры на фронтэнде.

**Comment by IrenJones** [comment]
@malinink 

я всё равно слабо поняла, как тут надо действовать
пусть лучше кто-нибудь ещё попробует это сделать, я вряд ли смогу

**Comment by malinink** [comment]
@IrenJones 
В субботу поднимите вопрос, либо сниму задачу либо обсудим что делать то в итоге надо.
