### ISSUE TITLE
Обработка хода со стороны клиента

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#119]
Родительская задача #
Исполнитель @

Описание
Валидация пришедшего [сообщения](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B2-%D0%B8%D0%B3%D1%80%D0%B5-1) turn и функция, выполняющая необходимые действия (передвижение фигуры/сбитой фигуры)

Теги: frontend

**Comment by malinink** [comment]
@Ananaskelly 
Так, погодите, если это по нашему протоколу - то долно быть указано что за протокол, т.к. хочется конкретики, либо я не понял что в итоге мы делаем.

**Comment by Ananaskelly** [comment]
поправила

**Comment by Ananaskelly** [comment]
+

**Comment by malinink** [comment]
@Ananaskelly 
Вы бы вначале задачу столбили, чтобы небыло проблем.
