### ISSUE TITLE
Создать модель и миграцию игровой информации пользователя

### ISSUE THREAD

**Issue by bubrick-old** [malinink/games#12]
#5

Модель [UserIngameInfo](https://github.com/malinink/games/wiki/Database) содержит
- **type_id** (integer) (внешний ключ, связан m:1 с GameType #11)
- **user_id** (integer) (внешний ключ, связан m:1 с User #6)
- game_rating (integer)
- games (integer)
- wins (integer)

связана m:1 с GameType #11, m:1 с User #6 
Теги: model

**Comment by IrenJones** [comment]
Я возьму это задание
