### ISSUE TITLE
Обработка хода со стороны сервера

### ISSUE THREAD

**Issue by artesby** [malinink/games#126]
Родительская задача #130
Исполнитель @

Описание
Создать контроллер Controller\Ajax\TurnController с функций turn(TurnRequest $msg), которая будет проверять возможность данного хода и совершать его в случае успеха.
Нужно декодировать json сообщение о ходе [$msg](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%B0--%D0%9E%D1%82%D1%87%D0%B5%D1%82-%D0%BE-%D1%81%D0%BE%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D0%BC-%D1%85%D0%BE%D0%B4%D0%B5) и вызывать для него метод модели Game validateTurn, возвращающий true\false.

Теги: controller

**Comment by malinink** [comment]
@artesby 
только - Controller\Ajax\TurnController
а то не будет никакого масштабирования
также напишите что именно мы должны проверить при валидации данных в 

также не согласен с методом как в контроллере так и в Game 
мы же в итоге сделем ход, поэтому метод - turn либо два метода - valudate и turn. Я за один метод.

**Comment by artesby** [comment]
@malinink

**Comment by malinink** [comment]
@artesby 
Намного подправил, я подумал что всёже сложно будет сделать быстро и правильно несколько методов, - лучше один. Но декомпозировать его в обзем случае не проблема, если будет большой разбивать на приватные методы - нужно.

**Comment by IrenJones** [comment]
+

**Comment by artesby** [comment]
@malinink 
я запутался
нам надо совершить 4 действия: декодировать сообщение, проверить корректность хода, обновить инфу в бд, отравить сообщение
декодировать в контроллере + вызывать метод валидации (который в модели)
проверять + обновлять + отправлять надо в модели
вот все 2 метода
так?

**Comment by malinink** [comment]
В текущей задаче мы остановились на реализации проверки базовой, и отправки сообщения.
Всё будет в одном публичном методе.

Я бы предложил в него уже передавать конкретные параметры. т.е. 
turn(user, figureId, x, y)

@IrenJones 
Это уж чтобы было ещё проще скоординироваться.

**Comment by IrenJones** [comment]
@malinink 

Вопрос
"в Game реализовать метод turn($msg)" - т.е. у нас два метода с одним названием будет
В модели Game
и в TurnController 

И при этом TurnController  принимает сообщение и отправляет уже данные, прошедшие валидацию, в функцию turn в модели Game, чтобы проверить возможность хода? 
Или уже наборот?

**Comment by malinink** [comment]
@IrenJones 
да, метода будет два, называться будут одинаково, но разные аргументы.
в контроллере - валидация, а в игре - `turn(user, figureId, x, y, typeId = null)`

**Comment by Ananaskelly** [comment]
Прощу прощения, что вмешиваюсь в Вашу беседу, но для того, кто будет реализовывать метод, принимающий сам запрос - там, как мне показалось, нужен ещё параметр, чтобы передавать фигуру, на которую пользователь хочет заменить пешку, если это возможно. Просто в протоколе этого параметра сейчас нет. Вернее есть, но только там, где мы уже клиентам рассылаем.

**Comment by malinink** [comment]
@Ananaskelly 
Согласен, подправил в комментарии выше.
