### ISSUE TITLE
Функция хода 

### ISSUE THREAD

**Issue by artesby** [malinink/games#127]
Родительская задача #130
Исполнитель @

Ожидает выполнения:
- [ ] #126

Описание
В модели Game реализовать метод turn($msg), выполняющий необходимые проверки запрашиваемого хода, как то:
- может ли фигура ходить данным образом, что она не съеден
- не получит ли игрок шах при этом
- существование id игры, что она не закончилась
- принадлежность x и у диапазону клеток доски
- что сейчас действительно ход игрока, отправившего запросто

возвращать true\false
в случае true отправить новое [сообщение](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B2-%D0%B8%D0%B3%D1%80%D0%B5) и применить ход (в бд)
аргумент - [см](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%B0--%D0%9E%D1%82%D1%87%D0%B5%D1%82-%D0%BE-%D1%81%D0%BE%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D0%BC-%D1%85%D0%BE%D0%B4%D0%B5)
информацию о фигурах и клетка см [тут](https://github.com/malinink/games/wiki/Database)

Теги: model

**Comment by malinink** [comment]
Ну собственно теже мысли, только немного подправьте название метода.

**Comment by artesby** [comment]
@malinink 
направил
