### ISSUE TITLE
Инициализация игры на стороне клиента

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#128]
Родительская задача #
Исполнитель @

Описание
Обработка сообщения с name [_init_](https://github.com/malinink/games/wiki/Protocol#%D0%A1%D1%82%D0%B0%D1%80%D1%82-%D0%B8%D0%B3%D1%80%D1%8B), функция осуществляющая расстановку фигур на поле, добавляющая логины игроков.

Теги: frontend

**Comment by malinink** [comment]
@Ananaskelly 
Не знаю кто правил протокол, но надо подправить, т.к. на пользователя нам должен передаваться не только логин - то ещё и его id, т.е. я бы передавал массив пользователей, и на каждого 3 параметра имя, ид, цвет

**Comment by Ananaskelly** [comment]
я, сейчас доделаю

**Comment by Ananaskelly** [comment]
и +
