### ISSUE TITLE
Создать модель и миграцию предпочтений пользователя

### ISSUE THREAD

**Issue by bubrick-old** [malinink/games#13]
#5

модель [UserDefault](https://github.com/malinink/games/wiki/Database) содержит
- **user_id** (integer) (внешний ключ, связан 1:1 с User #6 **id**)
- **type_id** (integer) (внешний ключ, связан m:1 с GameType #11 **id**)
- private (bool)

связана 1:1 с User #6, m:1 с GameType #11
Теги: model

**Comment by malinink** [comment]
Задача отменена, было принято решение сделать так #45
