### ISSUE TITLE
Поправить метод turnControl

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#146]
Родительская задача #139 
Исполнитель @

Описание
поправить отправку запроса на синхронизацию(вызывается [метод](https://github.com/malinink/games/blob/dev/public/js/GameControl/turnControl.js#L55), у которого сейчас другое название). 

Теги: frontend

**Comment by malinink** [comment]
@Ananaskelly 
Распишите задачу поподробнее, я вообще не могу понять о чем речь.

**Comment by Ananaskelly** [comment]
поправила, и там просто еще надо немного поправить, чтобы другое работало (подсветка клеток, куда можно ходить), поэтому я ишью отдельное сделала.

**Comment by Ananaskelly** [comment]
+
