### ISSUE TITLE
Обновление доски 

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#155]
Родительская задача #
Исполнитель 
Описание
Отправить на блейд данные и расставить фигуры для того игрока, кому инит не пришёл

Теги: backend, frontend, controller

**Comment by malinink** [comment]
@IrenJones 
Просто при загрузке игры, в случае если игра была начата - отображать все фигуры на доске из контроллера.
Не забыть про переворот доски для "белого" игрока.

**Comment by IrenJones** [comment]
Я не успеваю это сделать
Есть только доска через циклы и всё на данном этапе

**Comment by malinink** [comment]
Выкладывайте то, что успели сделать хотябы

**Comment by IrenJones** [comment]
[тут всё](https://github.com/malinink/games/compare/dev...IrenJones:feature155?expand=1)
