### ISSUE TITLE
Создать модель и миграцию игр пользователя

### ISSUE THREAD

**Issue by artesby** [malinink/games#16]
Родительская задача #5
модель [UserGame](https://github.com/malinink/games/wiki/Database) содержит:
- **user_id** (integer) (внешний ключ, связан m:1 с User #6 **id**)
- **game_id** (integer) (внешний ключ, связан m:1 с Game #8  **id**)
- color (bool)
- reserve_time (integer)

связана m:1 :
- **user_id** - User #6 **id**
- **game_id** - Game #8 **id**

Теги: model

**Comment by malinink** [comment]
@artesby 
Я не понял, вроде бы же хотели по итогу сделать many to many? Или опять передумали?
и да, отношения у вас будут что UG : U что UG G m:1 - оба!

**Comment by artesby** [comment]
@malinink 
да, мы решили сделать так по итогу
поправил отношение

**Comment by malinink** [comment]
@artesby 
А вверху подправить?
Просьба добавить соответствующие обратные связи в задачи по моделям Game и User а информацию о старых связях затереть.

**Comment by artesby** [comment]
@malinink 
чего-то направил

**Comment by artesby** [comment]
и за это возьмусь
