### ISSUE TITLE
Добавление поля и раздела для администраторов

### ISSUE THREAD

**Issue by learp** [malinink/games#18]
Нужно создать булевское поле у пользователя (users), обозначающее админ ли этот пользователь. Также добавить раздел для администрирования на сайте.

Теги: task

**Comment by malinink** [comment]
@learp 
А вот и нет, разбивайте задачу на компоненты:
- model view controller

т.е. как минимуму должно получится 3 задачи

тег - определенно не task

**Comment by learp** [comment]
вроде поправил
