### ISSUE TITLE
Добавить показатель "активной игры"

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#19]
Родительская задача #14
_Описание_
Необходимо добавить возможность для пользователя увидеть, есть ли у него активная игра на данный момент. 
Задача заключается в создании индикатора вверху страницы и написании функционала, который отслеживал бы состояние пользователя (наличие игры в данный момент или нет)

Задача связана с #26 
_Теги_:  view

**Comment by artesby** [comment]
+
