### ISSUE TITLE
#2 Database

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#2]
- создать модели
- представить структуру базы данных основываясь на идеях #1

**Comment by malinink** [comment]
@Ananaskelly Не надо создавать модели(я про PR), только схему!, а вот задачу со схемой - лучше распишите

**Comment by Ananaskelly** [comment]
Не совсем понятно, что значит лучше расписать.
Имеется ввиду расписать уже конкретно схему базы данных?

**Comment by malinink** [comment]
@Ananaskelly Нет, имею ввиду что надо понять что из себя должна представлять струкрура бд (модели?) и как это описать

**Comment by Ananaskelly** [comment]
Мы пришли к идее, что структура БД должна представлять примерно следующее:
должна быть таблица пользователей и таблица, где будет хранится история игр.
Таблица пользователя должна содержать : 
- id
- Логин 
- Пароль
- Email
- Дату последнего посещения ресурса
- Рейтинг игрока

Таблица с играми: 
- Название игры**
- id игры
- История
- Флаг публичная игра или нет
- Рейтинг игры (количество "лайков")
- id одного игрока
- id второго игрока

(последние два поля связывают эту таблицу с таблицей пользователей)

*\* возможно, нужна отдельная табличка с типами/названиями играми, что соответственно несколько поменяет структуру

**\* необходимо каким-то образом хранить друзей пользователя, но мы не смогли прийти к оптимальному решению данной проблемы пока

**Comment by malinink** [comment]
@Ananaskelly В идеале бы расписать поля сложные, 
например полностью непонятна ситуация с Историей.
Самый оптимальный вариант переложить на объекты и связи между объектами. Результат в вику. Если будут вопросы, до 23 я смогу что-то дельное ответить.

**Comment by Ananaskelly** [comment]
Не совсем понятно, что имеется в виду под объектами в данном случае

**Comment by malinink** [comment]
@Ananaskelly Ну например:
Студенты
- студенческий
- ф
- и
- о
  ...

Группы
- номер

Связи:
Студенты m:1 Группы (является участником)
Студенты 1:1 Группы (является старостой)

**Comment by Ananaskelly** [comment]
Над заданием работала вся группа, все принимали участие в обсуждении
