### ISSUE TITLE
Создание контроллера для раздела администратора

### ISSUE THREAD

**Issue by learp** [malinink/games#21]
Родительская задача #14

Создание контроллера и роута для раздела администратора. Добавить проверку поля isAdmin в контроллере (т.е. перед возвратом вьюшки проверить поле).

Теги: controller

**Comment by malinink** [comment]
@learp  @IrenJones
Есть ли разница между этой задачей и #26 ?

**Comment by IrenJones** [comment]
@malinink 
Так #26 это функция, которая доступна всем пользователям
Чтобы человек мог видеть, есть ли у него активная игра на данный момент

**Comment by malinink** [comment]
@IrenJones 
Ой, надо было идти спать, извиняюсь, я что-то напутал.

**Comment by artesby** [comment]
+
