### ISSUE TITLE
Создать миграцию для таблицы users

### ISSUE THREAD

**Issue by learp** [malinink/games#22]
Родительская задача #14
Задача зависит от #6 (т.е. нужно чтобы она была сделана)

Написать миграцию для users, добавить поле isAdmin.

Теги: model

**Comment by malinink** [comment]
@learp 
Определенно это надо сделать после выполнения задачи с изменением миграции пользователей с milstone на ближайшую субботу, укажите это

**Comment by artesby** [comment]
+
