### ISSUE TITLE
Добавление записей в Games-Type

### ISSUE THREAD

**Issue by learp** [malinink/games#24]
Родительская задача #14

Назначена: @Ananaskelly 
Подумать как и через что добавить записи в Games-Type (смотреть в сторону миграций). 
Добавить типы игры (короткие, длинные, обычные шахматы).

Теги: task (т.к. пока что подумать)

**Comment by malinink** [comment]
@learp 
А какие именно nипы до добавить надо? Перечислите хотябы...

**Comment by Ananaskelly** [comment]
Есть вопрос насчёт этого задания, прочитала в документации, что можно использовать метод change() и для этого нужно добавить doctrine/dbal в зависимости в composer.json. Это тот способ, которым предполагалось выполнение задания?

**Comment by malinink** [comment]
@Ananaskelly
Все немного проще https://laravel.com/docs/5.0/migrations#database-seeding

Малинин Константин

**Comment by Ananaskelly** [comment]
поняла, тогда я бы взялась за это задание
