### ISSUE TITLE
Функция состояния "активной игры"

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#26]
Родительская задача #14
_Описание_
Необходимо добавить возможность для пользователя увидеть, есть ли у него активная игра на данный момент. 
Задача заключается в написании функционала, который отслеживал бы состояние пользователя (наличие игры в данный момент или нет)

Задача связана с #19 
_Теги_:  controller

**Comment by malinink** [comment]
@IrenJones 
На паре надо будет решить вопрос со сылками между задачами
И добавьте пожалуйста родительскую задачу

**Comment by artesby** [comment]
+
