### ISSUE TITLE
#3 Frontend

### ISSUE THREAD

**Issue by artesby** [malinink/games#3]
Обдумать интерфейс сайта:
- дерево роутов и систему навигации
- внешний план страниц 

Основываясь на идеях #1

**Comment by malinink** [comment]
@artesby 
Сами страницы разрисовывать не надо, но схематично представить - да надо.

**Comment by artesby** [comment]
@malinink 
схематично = расположение и размер объектов на странице?

**Comment by malinink** [comment]
@artesby да, не надо ничего рисовать(только если не очень хочется), нас интересуют только области на страницах и их функционал.
Детальность областей зависит от их сложности,- чем более сложная облать - тем больше деталей нам необходимо узнать о ней.

**Comment by artesby** [comment]
в общем, над указанными пунктами работали:
- макеты страниц - Андрей Павлов, Влад Юревич
- роуты - Александр Тимофеев с консультациями у Матвея Старцева)
