### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#38]
Родительская задача #29
Исполнитель @

Описание
Создать view для странички, на которой пользователь оказывается после логина. Создать возможность поиска игры с выбранными параметрами (пока вроде как это тип игры и публичная или нет)

Задача связана с #39 
Теги: view

**Comment by malinink** [comment]
Смотрим на обсуждение тут #39 

Будет несколько view

также я бы указал что эта задача зависит от 39, подправьте плз.

**Comment by Ananaskelly** [comment]
Не совсем ясно какие надо сделать задачи на view, например. Стоит опираться на созданные макеты?

**Comment by malinink** [comment]
@Ananaskelly 
Да, но, наверное, если нет жаждующих делать красиво, то пока что делаем функциональный дизайн, т.е. только с элементами бутстрапа и не более.

**Comment by Ananaskelly** [comment]
+
