### ISSUE TITLE
Сделать миграцию на изменение значений

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#43]
Родительская задача #24
Исполнитель @

Описание
Добавить типы игр.

Теги: model

**Comment by malinink** [comment]
@Ananaskelly 
Можно ли эту задачу удалить, а #24 изменить, чтобы не плодить кучу задач.

Т.е. надо чтобы в задаче было и подумать и сделать!

Если Вы не сможете подправить задачу #24 обратитесь к @learp не думаю что он Вам откажет.

Сответственно после внесения изменений текущую задачу закрыть

**Comment by learp** [comment]
Поправил.
