### ISSUE TITLE
Сделать миграцию на добавление полей в модель User

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#45]
Родительская задача #
Исполнитель @

Описание
Сделать миграцию на добавление полей в модель [User](https://github.com/malinink/games/wiki/Database)
Поля: 
- default_game_type_id (integer) (внешний ключ, связан m:1 с [GameType](https://github.com/malinink/games/wiki/Database) #11 id)
- default_game_private (bool)

Теги: model

**Comment by malinink** [comment]
@Ananaskelly 
Круто что меняете сразу же модели в Вики, это верно!

Но в описании задачи ошибка, private bool - это очевидно просто поле и не является связью.

**Comment by Ananaskelly** [comment]
В вики - это @bubrick работа)

**Comment by malinink** [comment]
@Ananaskelly 
Я бы назвал поля по-другому, т.к. потом будет не понятно каково их значение.
Например:
dafault_game_type_id
default_game_private

Согласны что так не будет двусмысленности?

**Comment by Ananaskelly** [comment]
подправила описание

**Comment by malinink** [comment]
@Ananaskelly 
Теперь полностью согласен

**Comment by Ananaskelly** [comment]
А вот у нас есть уже созданная модель Game Types, где есть метод UserDefaults(), который теперь не нужен. Надо ли сделать issue на изменение этой модели?

**Comment by malinink** [comment]
@Ananaskelly 
Определенно, я бы даже его поставил на milestone в эту субботу, т.к. с моделями то точно неприятностей уже быть не должно.

**Comment by Ananaskelly** [comment]
+
