### ISSUE TITLE
Тестирование модели Game

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#46]
Родительская задача #25 
Исполнитель @

Описание
Написать тесты для модели [Game](https://github.com/malinink/games/wiki/Database) - проверить, что модель добавляется в базу данных и связи с [Turn Info](https://github.com/malinink/games/wiki/Database), [Board Info](https://github.com/malinink/games/wiki/Database), [User Game](https://github.com/malinink/games/wiki/Database) работают корректно.

Теги: model

**Comment by malinink** [comment]
@Ananaskelly 
Не все связи модели Games перечислены, очевидно что в вики не все обратные проставлены у модели, а проверить то надо все.
Просьба подправить описание в вики (добавить обратных связей у моделей где их нехватает)
И подправить все задачи по тестированию этих моделей. (если где чего не хватает, потом тут отпишитесь и я проверю ещё раз задачи.)
Например у модели Games очевидно должна быть связь на:
- BoardInfo
- TurnInfo

**Comment by Ananaskelly** [comment]
Кажется, поправила

**Comment by Ananaskelly** [comment]
+

**Comment by Ananaskelly** [comment]
У меня возникла небольшая проблема с моделью Board Info (и c Turn Info аналогично), у них нет id и primary key и из-за этого метод delete() для них не работает. Надо ли добавить id (просто в вики они не указаны и может надо другой путь найти)?

**Comment by malinink** [comment]
@Ananaskelly 
Да надо добавить, и как я только PK проглядел...
Докатите до последней версии dev, там есть небольшие правки моделей Ваших
