### ISSUE TITLE
Тестирование модели User Game

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#47]
Родительская задача #25
Исполнитель @

Описание
Написать тесты для модели [User Games](https://github.com/malinink/games/wiki/Database) - проверить, что модель добавляется в базу данных.

Теги: model

**Comment by learp** [comment]
+

**Comment by learp** [comment]
@malinink 
И с этим, тут не протестирована только связь User Games с User, но, опять же, тот кто пишет Usera её протестит.

**Comment by malinink** [comment]
@learp 
Да, но Вы можете договорится с @Ananaskelly и проверить эту связь в рамках этой задачи.
В таком случае другую задачу необходимо подрпавить.
