### ISSUE TITLE
Тестирование модели Board Info

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#49]
Родительская задача #25
Исполнитель @

Описание
Написать тесты для модели [Board Info](https://github.com/malinink/games/wiki/Database) - проверить, что модель добавляется в базу данных.

Теги: model

**Comment by learp** [comment]
+

**Comment by learp** [comment]
@malinink
Хотел бы уточнить такой момент, сел писать и увидел, что создан тест BoardInfoWithGameRelationTest. Мне разве надо что-то писать?)
Наверное следует переписать задания, т.к. мы решили тестировать связи.

**Comment by malinink** [comment]
@learp 
Да видимо произошел дубляж, действительно.
