### ISSUE TITLE
Тестирование модели Game Types

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#50]
Родительская задача #25
Исполнитель @

Описание
Написать тест для модели [Game Types](https://github.com/malinink/games/wiki/Database) - проверить, что она добавляется в базу данных, проверить связи с [User](https://github.com/malinink/games/wiki/Database),  [UserIngameInfo](https://github.com/malinink/games/wiki/Database), [Game](https://github.com/malinink/games/wiki/Database).

Теги: model

**Comment by malinink** [comment]
+

**Comment by malinink** [comment]
Добавил файл для тестирования.
Залил тестирование связи Game - GameType

Остальная часть задачи ждет исполнителя

**Comment by IrenJones** [comment]
+
