### ISSUE TITLE
Тестирование модели User Ingame Info

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#51]
Родительская задача #25
Исполнитель @IrenJones

Описание
Написать тесты для модели [User Ingame Info](https://github.com/malinink/games/wiki/Database) - проверить, что модель добавляется в базу данных и связи с [Game Types](https://github.com/malinink/games/wiki/Database) и [User](https://github.com/malinink/games/wiki/Database) работают корректно.

Теги: model

**Comment by IrenJones** [comment]
+
