### ISSUE TITLE
Изменение модели Game Types

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#52]
Родительская задача #
Исполнитель @Ananaskelly 

Ждем задачи 
- [ ] #45

Описание
Необходимо изменить связь данной модели с User Defaults на связь с [User](https://github.com/malinink/games/wiki/Database) (id связан 1:m с [User](https://github.com/malinink/games/wiki/Database) #45 default_game_type_id)

Теги: model

**Comment by Ananaskelly** [comment]
и тут тогда поправлю

**Comment by malinink** [comment]
@Ananaskelly 
По итогу м все равно будем вынуждены ждать когда кто-нибудь разрешит задачу #45 иначе все равно ничего работать не будет толком.
