### ISSUE TITLE
Создать миграцию модели пользователей

### ISSUE THREAD

**Issue by artesby** [malinink/games#6]
#5

в модель [User](https://github.com/malinink/games/wiki/Database) добавить поля:
- registration_date (date)
- last_visit (datetime)

связать отношением 1:1 с моделями:
- **id** - UserDefault #13 **user_id** 

1:m
- **id** - UserIngameInfo #12 **user_id**
- **id** - UserGame #16 **user_id**

m:m
- **id** - User #6 **id** (дружба)

Теги: model

**Comment by malinink** [comment]
@artesby 
Предлагаю в начале каждой задачи делать ссылку на родительскую задачу #4 в нашем случае
Следует упомянуть что модель users уже есть, а то, что тут указываете Вы - непосредственно её дополнение, т.е. только миграция.
Теги как я понял проставлять он не дает? (тогда давайте писать в конце предполагаемые теги)

По содержимому на текущий момент:
- модель User уже есть, предлагаю отталкиваться от того что в ней находится, т.е. переименовать модели по которым выставлены задачи.

Предлагаю поправить только эту задачу и поглядеть что выйдет, а потом уже взяться за остальные.

**Comment by artesby** [comment]
Я же и написал создать миграцию модели, в других случаях я писал создать и модель и миграцию. просто написал, что по итогу пользователь должен содержать, вместо перечисления что удалить\переименовать.
Лейбл поставить не дает, да.

> модель User уже есть, предлагаю отталкиваться от того что в ней находится, т.е. переименовать модели по которым выставлены задачи.

это вообще не понял)

**Comment by malinink** [comment]
@artesby Суть в том, что в текущей модели User есть уже определенный набор полей, как то 
- email
  У Вас же это поле находится в модели PersonalInfo
  Я пытался высказать мысль, что это поле перенести так вот просто не получится, оно должно остаться в модели User.
  В связи с этим определенно надо будет внести коррективы в модели и их поля.

**Comment by artesby** [comment]
но это для нас тоже кучу вопросов порождает, почему сложно перенести, что еще в схемке нужно менять (пароль?), почему мы это не увидели на паре

**Comment by malinink** [comment]
Потому что не подумали об этом, погодите:
- Надо исходить из того что у нас уже есть, т.к. это базовый функционал Ларавеля, нет большого смысла придумать свои "уникальные" модели, а потмом переписывать функционал аутентификаци.
- Т.е. модель User уже есть

Моё предложение User объект использовать как средство для идентификации пользователя. И опять давайте я не буду думать наперед, будете налетать на проблемы сами. тогда #7 пока что лишняя. Не используем и убираем из всех связей.

**Comment by artesby** [comment]
возьмусь за это задание
