### ISSUE TITLE
Отображение доски

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#70]
Исполнитель @Ananaskelly 

Описание
Отображение доски и фигур, анимация игрового хода, игрового процесса 
Теги:

**Comment by Ananaskelly** [comment]
+

**Comment by malinink** [comment]
@Ananaskelly 
Я всё конечно понимаю, но немного больше уделите процессу описания задачи!
Постевьте описание такое, чтобы по нему почти любой смог бы сделать такой же PR как у Вас!
Тег выбрать, да?

**Comment by Ananaskelly** [comment]
Я пыталась что-то написать в задаче, но я не могу придумать и сформулировать, что ещё должно быть в описании
