### ISSUE TITLE
Метод модели Game

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#75]
Исполнитель @Ananaskelly

Описание
Создать метод, возвращающий чей ход был последним в текущей игре пользователя. 

Теги: model

**Comment by Ananaskelly** [comment]
+

**Comment by malinink** [comment]
@Ananaskelly 
Ещё выскажу тут следующую мысль, надо подумать необходим ли этот метод, т.е. будет ли реальная необходимость его использовать? 
Или же нам надо будет отвечать на вопрос чей сейчас ход?
А может быть даже, сейчас мой ход?
т.е. отчет ход черных или белых нам как, пользователям мало чего дает. Но это не означает что метод не нужен. Я просто предлагаю подумать.

**Comment by Ananaskelly** [comment]
Мне казалось, что мы ведь будем знать, каким пользователь играет цветом, поэтому информации о цвете последнего походившего будет достаточно.
Или надо проверять и цвет, которым пользователь играет и возвращать true или false?

**Comment by malinink** [comment]
Чтобы узнать цвет игрока - тожа надо делать метод, выходит что метод длуя того чтобы узнать цвет, а потом по цвету узнавать чей ход? 
Так тоже будет работать, вопрос в том как проще и какие методы нам действительно будут нужны?
Я к чему, можно реализовать метод, просто если потом окажется что он не к месту - будет жалко.
