### ISSUE TITLE
Создать модель и миграцию игры

### ISSUE THREAD

**Issue by artesby** [malinink/games#8]
#5

модель [Game](https://github.com/malinink/games/wiki/Database) содержит
- **id** (increments) (первичный, связан 1:m с UserGame #16 **user_id**, TurnInfo #9 **game_id**, BoardInfo #10 **game_id**)
- **type_id** (tinyInteger) (внешний, связан m:1 с GameType #11  **id**)
- private (bool)
- time_started (datetime)
- time_finished (datetime)
- winner (bool)
- bonus (tinyInteger)

связана 1:m 
- **id** - UserGame  #16 **game_id**
- **id** - TurnInfo #9 **game_id**
- **id** - BoardInfo #10 **game_id**

m:1 
- **type_id** - GameType #11 **id**

Теги: model

**Comment by malinink** [comment]
Предлагаю подумать как будет выбирать список сыгранных игр одним конкретным игроком

**Comment by artesby** [comment]
будет выбираться по айди, искать будем в одной из двух колонок, дубликатов там не будет, тк мы решили записывать в первую - игрока белых, во вторую - черных. или не в этом косяк?

**Comment by malinink** [comment]
@artesby 
Ну проблема то очевидно есть, это то, о чем мы не подумали заранее.
Ладно давайте действовать итерационно. Пусть все останется так как есть сейчас (а про текущую задачу).
Но если будет настроение поищите подвох, он есть!

**Comment by artesby** [comment]
@malinink 
Имеется ли в виду, что мы не будем знать точно, в какой колонке искать оппонента для отображения?

**Comment by malinink** [comment]
@artesby 
Ну, во-первых, да, но это решается обычным условием, а вот например как бы вывести список последних сыграных игр?

**Comment by artesby** [comment]
@malinink 
первое что приходит в голову - из выборки по id игрока выбрать n максимальных по id игры, оно же инкрементится 
либо по дате

**Comment by malinink** [comment]
@artesby 
Завтра обсудим!

**Comment by Ananaskelly** [comment]
хотела бы взять это задание
