### ISSUE TITLE
Переподключение клиента 

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#86]
Родительская задача #89 
Исполнитель @

Описание 
Найти библиотеку, которая обеспечивала бы переподключение клиента при разрыве соединения с ws-сервером

Теги: frontend

**Comment by malinink** [comment]
@IrenJones 
Добавил теги backend & frontend
подправьте в описании на нужный.

**Comment by IrenJones** [comment]
+

**Comment by IrenJones** [comment]
@malinink 

Есть [вот такой](https://github.com/joewalnes/reconnecting-websocket) вариант
Здесь правда несовсем понятно, будет ли переподключение конкретного пользователя: сможем ли мы записать какую-либо информацию, чтобы идентифицировать, что данный клиент уже есть, и не создавать нового

**Comment by malinink** [comment]
@IrenJones 
Никогда не использовал эту, но судя по описанию все возлагаемые на WS задачи она позволит решить конфигурацией, так что это то, что нужно.
А по поводу клиента, - после реконнекта всегда надо будет заново проходить всю процедуру аутентификации клиента через токен и оформлять подписку. Это нормальная практика.
