### ISSUE TITLE
Удаление информации с сервера

### ISSUE THREAD

**Issue by IrenJones** [malinink/games#87]
Родительская задача #89 #94 
Исполнитель @

Описание
Необходимо продумать и реализовать механизм удаления данных об игре после того, как игра закончена

Теги: backend

**Comment by malinink** [comment]
@IrenJones 
Явно этой информации недостаточно для того чтобы понять что требуется, напишите хотябы откуда эта информация будет появляться.
Или же добавьте задачу на связывание эигр и клиентов, а отсюда туда ссылку.
Тут дам подсказку - это всяко бекенд.

**Comment by malinink** [comment]
Удаление происходит в PushServerSocket

**Comment by malinink** [comment]
Почему закрыли то? это коментарий к тому где реализовывать задачу!

**Comment by IrenJones** [comment]
@malinink 
Игра и так уже вроде удаляется
Или ещё тут что-то требуется?

**Comment by malinink** [comment]
@IrenJones 
Данные об удалении которых в этой задаче идет речь, ещё даже не добавляются!
Это связи между играми и подписчиками.
Возможно что эту задачу и решит кто-то кто будет реализовывать протокол, но лучше пусть она останется, пока соответствующий протокол не будет сделан. А так поглядим.

**Comment by artesby** [comment]
+
