### ISSUE TITLE
Создать модель и миграцию игрового хода

### ISSUE THREAD

**Issue by artesby** [malinink/games#9]
#5

модель [TurnInfo](https://github.com/malinink/games/wiki/Database)
- **game_id** (integer) (внешний ключ, связан m:1 с Game #8 **id**)
- turn_number (smallInteger)
- move (smallInteger)
- options (tinyInteger)
- turn_start_time (datetime)
- user_turn (bool)

связана m:1 
- **game_id**  - Game #8 (**id**)

Теги: model

**Comment by malinink** [comment]
Ссылочку бы на описание в вики, если там есть таковое

**Comment by IrenJones** [comment]
Я возьму это задание
