### ISSUE TITLE
Запрос токена

### ISSUE THREAD

**Issue by artesby** [malinink/games#91]
Родительская задача #89 
Связана с #93
Исполнитель @

Описание
Реализовать статический метод getIdentificationToken модели Token, генерирующий токен для пользователя (указывается в качестве параметра) и сохраняющий его бд. Уделить внимание генерации самого токена и проверке на его уникальность. Хранить необходимо в течение короткого времени, напр 30секунд.
запрос и форма ответа [тут](https://github.com/malinink/games/wiki/Protocol#%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81-%D0%BD%D0%B0-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0--%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0)

Теги: model

**Comment by malinink** [comment]
Метод реализуем в модели Token, параметр - User, возвращаем саму модель токена.
метод статический. 
Уделить внимание генерации самого токена и проверке на его уникальность.
С большой вероятностью сам токен - PK.

**Comment by learp** [comment]
+

**Comment by learp** [comment]
Насчет генерации токена, почему нельзя сделать токеном id user'а? чем это будет плохо?
Если id нежелательно, то можно вбить алфавит в строку, рандомно выбирать индексы и формировать строку, потом смотреть в БД.
и какие вообще на токен ограничения? (длина строки или еще что-то)

**Comment by malinink** [comment]
Потому что это не безопасно, я смогу представится любым пользователем зная его id
Токен должен быть уникальной и довольно-таки длинной строкой. 
Думаю что что-то вроде bin2hex(random_bytes(100)) подойдет

**Comment by learp** [comment]
Нашел в ларавеле str_random(длина строки), наверное её использую.

**Comment by malinink** [comment]
Согласен
