### ISSUE TITLE
Создать модель и миграцию токенов

### ISSUE THREAD

**Issue by artesby** [malinink/games#93]
Родительская задача #89 
Исполнитель @

Описание
Создать модель Token  
- token (string, unique) - первичный
- user_id (integer, внешний, связан m:1 с User **id**)
- expiration_date (dateTime)

связана m:1  **user_id**  -  User #6 (**id**)

Теги: model

**Comment by malinink** [comment]
Указывайте верно теги.
как минимум надо ещё и время годности хранить - expirationDate

**Comment by artesby** [comment]
@malinink 
подправил чего-то

**Comment by learp** [comment]
+
