### ISSUE TITLE
Передача хода

### ISSUE THREAD

**Issue by artesby** [malinink/games#97]
Родительская задача #100
Исполнитель @

Описание

Класс, который будет обрабатывать запросы с name _turn_. Получает информацию о [ходе игрока](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%B0--%D0%9E%D1%82%D1%87%D0%B5%D1%82-%D0%BE-%D1%81%D0%BE%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D0%BC-%D1%85%D0%BE%D0%B4%D0%B5) и проверяет его валидность. Сообщает о результате проверки и в случае успеха отправляет [информацию](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B2-%D0%B8%D0%B3%D1%80%D0%B5) о ходе ws серверу. WS [рассылает](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4-%D0%B2-%D0%B8%D0%B3%D1%80%D0%B5-1) ход клиентам.
Класс должен реализовывать интерфейс #98
Формат запроса [тут](https://github.com/malinink/games/wiki/Protocol#%D0%A5%D0%BE%D0%B4)

Теги: backend

**Comment by malinink** [comment]
Подправьте задачу ориентируясь на #101

**Comment by artesby** [comment]
+
