### ISSUE TITLE
Protocol Interface

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#98]
Родительская задача #89
Исполнитель @

Описание
Создать интерфейс, который будут имплементить все классы, обрабатывающие сообщения. Должен быть **конструктор**, которому передается само сообщение - _Array $data_, клиент - _ConnectionInterface $client_, наш ws сервер - _PushServerSocket $server_. И **метод compile()**, который будет обрабатывать сообщение, в зависимости от его типа.  

Теги: backend

**Comment by artesby** [comment]
+
