### ISSUE TITLE
изменить метод onMessage

### ISSUE THREAD

**Issue by Ananaskelly** [malinink/games#99]
Родительская задача #89
Исполнитель @

Описание
Надо добавить проверки на пришедший запрос - проверять, что формат - _JSON_ и в нем есть два ключа - _name_ и _data_. Потом проверять, что для данного типа запроса существует обработчик и вызывать его.

Задача связана с #98
Теги: backend

**Comment by malinink** [comment]
Задача связана с #98 
Необходимо узнать пространство имен классов протоколов.

**Comment by IrenJones** [comment]
+

**Comment by IrenJones** [comment]
@malinink 

Я не совсем поняла, каким именно образом должны происходить проверки (и каким именно образом отлавливать ошибки)

``` php
public function onMessage($data, $client)
{
        $data_js = json_decode($data, true);
        if ($data_js != null){
            if (isset($data_js['name']) && isset($data_js['data'])){

                $name=$data_js['name'];
                switch ($name) {
                    case "token":
                        //call
                        break;
                    case "authentification":
                        //call
                        break;
                    case "subscribe":
                        //call
                        break;
                    case "synchronize":
                        //call
                        break;
                    case "turn":
                        //call
                        break;
                    default:
                        echo sprintf('there isnt handler for'. PHP_EOL,$data_js['name']);
                        break;
                }
            }
        }
}
```

**Comment by malinink** [comment]
Не совсем, давайте представим, что у нас есть уже готовый класс протокола:

``` php
\Name\space\Token
```

Предположим что мы будем учитывать и искать классы протокролов только в этом пространстве имен, если такого класса нет - значит ошибка в запросе.

Тогда остается только проверить наличие класса `class_exists`
создать его экземпляр, и проверить что он реализует интерфейс `instanceof`

Если оба условия выполнены - передаем управлние классу, если нет - генерируем исключение и возвращаем ошибку.

Также стоит отлавливать все ошибки при передаче управления(ака вызове метода класса протокола). (подмайте как уместить все в один единственный try catch блок, если не выйдет я подскажу.)

**Comment by malinink** [comment]
Обратите внимание на [такое](https://github.com/malinink/games/pull/106/files) расположение протоколов, мне пространство имен нравится. Поэтому остановимся именно на таком варианте.
